services:

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
    restart: unless-stopped
    command: >
      etcd
      -advertise-client-urls=http://0.0.0.0:2379
      -listen-client-urls=http://0.0.0.0:2379
      -data-dir=/etcd
    volumes:
      - etcd_data:/etcd
    networks:
      - dyana-network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:2379/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    restart: unless-stopped
    command: minio server /data
    volumes:
      - minio_data:/data
    networks:
      - dyana-network
    ports:
      - "9001:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.6
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
      - minio

    restart: unless-stopped
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - dyana-network
    ports:
      - "19530:19530"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  dyana-network:
    name: dyana-network
    driver: bridge

volumes:
  etcd_data:
    name: etcd_data
  minio_data:
    name: minio_data
  milvus_data:
    name: milvus_data
